# Generated by Django 4.0.1 on 2022-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('request_id', models.AutoField(db_column='request_id', primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, db_column='datetime', null=True)),
                ('name', models.CharField(blank=True, db_column='name', max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, db_column='mobile', max_length=30, null=True)),
                ('company', models.CharField(blank=True, db_column='company', max_length=30, null=True)),
                ('jobtitle', models.CharField(blank=True, db_column='jobtitle', max_length=30, null=True)),
                ('product', models.CharField(blank=True, db_column='product', max_length=100, null=True)),
                ('inquiry', models.CharField(blank=True, db_column='inquiry', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntradayPrice5Min',
            fields=[
                ('obsdatetime', models.DateTimeField(blank=True, db_column='ObsDateTime', null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
            ],
            options={
                'db_table': 'Intraday_Price5min',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IntradayTaRisk',
            fields=[
                ('obsdatetime', models.DateTimeField(blank=True, db_column='ObsDateTime', null=True)),
                ('cat', models.CharField(blank=True, db_column='Cat', max_length=100, null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('step', models.FloatField(blank=True, db_column='Step', null=True)),
                ('cl', models.FloatField(blank=True, db_column='Cl', null=True)),
                ('vargauss', models.FloatField(blank=True, db_column='VaRGauss', null=True)),
                ('varstdt', models.FloatField(blank=True, db_column='VaRstdt', null=True)),
                ('varnts', models.FloatField(blank=True, db_column='VaRNTS', null=True)),
                ('cvargauss', models.FloatField(blank=True, db_column='CVaRGauss', null=True)),
                ('cvarstdt', models.FloatField(blank=True, db_column='CVaRstdt', null=True)),
                ('cvarnts', models.FloatField(blank=True, db_column='CVaRNTS', null=True)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
                ('ntstailrisk', models.FloatField(blank=True, db_column='NTSTailRisk', null=True)),
            ],
            options={
                'db_table': 'Intraday_TA_Risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('adjclose', models.FloatField(blank=True, db_column='AdjClose', null=True)),
                ('cat', models.CharField(blank=True, db_column='Cat', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Price_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Risk5Min',
            fields=[
                ('obsdatetime', models.DateTimeField(blank=True, db_column='ObsDateTime', null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
                ('tailriskchg', models.FloatField(blank=True, db_column='TailRiskChg', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('pricechg', models.FloatField(blank=True, db_column='PriceChg', null=True)),
                ('weather', models.CharField(blank=True, db_column='Weather', max_length=100, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Risk_5min',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskDay',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('cat', models.TextField(blank=True, db_column='Cat', null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
                ('tailriskchg', models.FloatField(blank=True, db_column='TailRiskChg', null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('pricechg', models.FloatField(blank=True, db_column='PriceChg', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('weather', models.CharField(blank=True, db_column='Weather', max_length=100, null=True)),
                ('weather_1', models.CharField(blank=True, db_column='Weather_1', max_length=100, null=True)),
                ('weather_2', models.CharField(blank=True, db_column='Weather_2', max_length=100, null=True)),
                ('weather_3', models.CharField(blank=True, db_column='Weather_3', max_length=100, null=True)),
                ('weather_4', models.CharField(blank=True, db_column='Weather_4', max_length=100, null=True)),
                ('weather_5', models.CharField(blank=True, db_column='Weather_5', max_length=100, null=True)),
                ('weather_6', models.CharField(blank=True, db_column='Weather_6', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Risk_Day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskExchange',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('exchange', models.TextField(blank=True, db_column='Exchange', primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, null=True)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
                ('tailriskchg', models.FloatField(blank=True, db_column='TailRiskChg', null=True)),
                ('weather', models.CharField(blank=True, db_column='Weather', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Risk_Exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaRisk',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('cat', models.CharField(blank=True, db_column='Cat', max_length=50, null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('step', models.IntegerField(blank=True, db_column='Step', null=True)),
                ('cl', models.FloatField(blank=True, db_column='Cl', null=True)),
                ('vargauss', models.FloatField(blank=True, db_column='VaRGauss', null=True)),
                ('varstdt', models.FloatField(blank=True, db_column='VaRstdt', null=True)),
                ('varnts', models.FloatField(blank=True, db_column='VaRNTS', null=True)),
                ('cvargauss', models.FloatField(blank=True, db_column='CVaRGauss', null=True)),
                ('cvarstdt', models.FloatField(blank=True, db_column='CVaRstdt', null=True)),
                ('cvarnts', models.FloatField(blank=True, db_column='CVaRNTS', null=True)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
            ],
            options={
                'db_table': 'TA_Risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TARiskCorr',
            fields=[
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('rank_1', models.CharField(blank=True, db_column='rank_1', max_length=50, null=True)),
                ('rank_2', models.CharField(blank=True, db_column='rank_2', max_length=50, null=True)),
                ('rank_3', models.CharField(blank=True, db_column='rank_3', max_length=50, null=True)),
                ('rank_4', models.CharField(blank=True, db_column='rank_4', max_length=50, null=True)),
                ('rank_5', models.CharField(blank=True, db_column='rank_5', max_length=50, null=True)),
                ('rank_6', models.CharField(blank=True, db_column='rank_6', max_length=50, null=True)),
                ('rank_7', models.CharField(blank=True, db_column='rank_7', max_length=50, null=True)),
                ('rank_8', models.CharField(blank=True, db_column='rank_8', max_length=50, null=True)),
                ('rank_9', models.CharField(blank=True, db_column='rank_9', max_length=50, null=True)),
                ('rank_10', models.CharField(blank=True, db_column='rank_10', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TA_Risk_Corr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaRiskExchange',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('exchange', models.TextField(blank=True, db_column='Exchange', primary_key=True, serialize=False)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, null=True)),
                ('vargauss', models.FloatField(blank=True, db_column='VaRGauss', null=True)),
                ('varstdt', models.FloatField(blank=True, db_column='VaRstdt', null=True)),
                ('varnts', models.FloatField(blank=True, db_column='VaRNTS', null=True)),
                ('cvargauss', models.FloatField(blank=True, db_column='CVaRGauss', null=True)),
                ('cvarstdt', models.FloatField(blank=True, db_column='CVaRstdt', null=True)),
                ('cvarnts', models.FloatField(blank=True, db_column='CVaRNTS', null=True)),
                ('tailrisk', models.FloatField(blank=True, db_column='TailRisk', null=True)),
                ('weatherscore30', models.DecimalField(blank=True, db_column='WeatherScore30', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore90', models.DecimalField(blank=True, db_column='WeatherScore90', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore180', models.DecimalField(blank=True, db_column='WeatherScore180', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore365', models.DecimalField(blank=True, db_column='WeatherScore365', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore730', models.DecimalField(blank=True, db_column='WeatherScore730', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'TA_Risk_Exchange',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherScore',
            fields=[
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
                ('cat', models.TextField(blank=True, db_column='Cat', null=True)),
                ('ticker', models.CharField(blank=True, db_column='Ticker', max_length=50, primary_key=True, serialize=False)),
                ('step', models.IntegerField(blank=True, db_column='Step', null=True)),
                ('weatherscore30', models.DecimalField(blank=True, db_column='WeatherScore30', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore90', models.DecimalField(blank=True, db_column='WeatherScore90', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore180', models.DecimalField(blank=True, db_column='WeatherScore180', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore365', models.DecimalField(blank=True, db_column='WeatherScore365', decimal_places=2, max_digits=5, null=True)),
                ('weatherscore730', models.DecimalField(blank=True, db_column='WeatherScore730', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Weather_Score',
                'managed': False,
            },
        ),
    ]
